# https://typescript-eslint.io/docs/linting/
root: true
env:
  node: true
  es2022: true
  browser: true
parser: '@typescript-eslint/parser'
plugins:
  - import
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - prettier
parserOptions:
  sourceType: module
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
    impliedStrict: true
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
        - tsconfig.node.json
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
