root: true
env:
  node: true
  es2021: true
  browser: true
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: tsconfig.json
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
    impliedStrict: true
ignorePatterns: vite.config.ts
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.js'
      - '.tsx'
      - '.jsx'
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.json
