root: true
env:
  node: true
  es2021: true
  browser: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - prettier
parserOptions:
  project:
    - tsconfig.json
    - tsconfig.node.json
  sourceType: module
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
    impliedStrict: true
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.json
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
