# https://prettier.io/docs/en/configuration.html
# https://github.com/trivago/prettier-plugin-sort-imports
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrderParserPlugins:
  - jsx
  - typescript
  - classProperties
  - decorators-legacy
importOrder:
  - '^(.*)[.]css$'
  - '^(.*)[.]scss$'
  - '^react$'
  - '^react-dom$'
  - '<THIRD_PARTY_MODULES>'
  - '^@[/](.*)$'
  - '^[.][/](.*)$'
