printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
xmlSelfClosingSpace: true
xmlWhitespaceSensitivity: ignore
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrderParserPlugins:
  - jsx
  - typescript
  - classProperties
  - decorators-legacy
importOrder:
  - '^(.*)[.]css$'
  - '^(.*)[.]scss$'
  - '^react$'
  - '^@(.*)$'
  - '<THIRD_PARTY_MODULES>'
  - '^@[/](.*)$'
  - '^[.][/](.*)$'
